settings:
  # run predictions over unseen data to see how well it performs, set False to skip 
  oos: True
  # number of passes to make when retraining on the last previous months oos data for optimizing predictions
  # for the forthcoming month, will do [n] simulations and pick the best result for the updated population
  # make 0 to skip this step
  retrainPasses: 10
  RAMDrive: r
  InSample:    
    minProfit: 0
    minWinRate: 50
    minTicksPerTrade: 2
  OOS:
    minProfit: 0
    minWinRate: 50
    minTicksPerTrade: 2
  # optional, list of markets to trade from raw, this allows you to keep csv data for multiple markets in
  #  raw folder but simluate on only specific data sets 
  market: 
    - XTIUSD-D  
    
default:
  # how many robots in your population
  populationDesiredSize: [10000,20000,30000,40000,50000,60000,70000,80000,90000,100000]
  # data loookback (offset), must be a list of integers, number of bars in your data Genotick looks back to train 
  # look back 1 month, 1 quarter (3 months) (+- 65 trading days), half year (6 months) [+- 124 trading days] or 1 year (12 months) [+- 256 trading days]
  dataMaximumOffset: [20,65,124,256]
  # train between these time points in your source data
  # all time points after the end time will be used as OOS data to evaluate the robots
  startTimePoint: 20100101
  endTimePoint: 20181231
    
EURUSD-H1:
  dataMaximumOffset: [8,12,24,48]
  startTimePoint: 20190301000000
  endTimePoint: 20190531230000
  
XTIUSD-D:
  startTimePoint: 20100502
  endTimePoint: 20181231
  populationDesiredSize: [10000]
  dataMaximumOffset: [5,10,20]

# definitions of various intrumenrts that will be traded, just to provide more human friendly output
# this works by assuming the base market name is the instrument name, thus the piece before the -
# matching in done in order using a regex 
# e.g.   XTIUSD-D  will be mapped to the instrument XTIUSD 
#        and EURUSD will be mapped to [a-z]+
#        XTIUSD won't be matched to EURUSD as XTIUSD is higher in list
#
#  multipler - used to convert fractional ticks into whole numbers, e.g.  100 for crude or 10000 for 5 digit forex
instruments:  
  # pepperstone WTI crude oil
  XTIUSD:
    multiplier: 100
    