default:
    # how many robots in your population
    populationDesiredSize: [10000,20000,30000,40000,50000,60000,70000,80000,90000,100000]
    # data loookback (offset), must be a list of integers, number of bars in your data Genotick looks back to train 
    # look back 1 month, 1 quarter (3 months) (+- 65 trading days), half year (6 months) [+- 124 trading days] or 1 year (12 months) [+- 256 trading days]
    dataMaximumOffset: [20,65,124,256]
    # train between these time points in your source data
    startTimePoint: 20100101
    endTimePoint: 20181231
    ramdrive: r